/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.jxareas.konnect.ui;

/**
 *
 * @author Jon Areas, @jxareas
 */
public class FormLogin extends javax.swing.JFrame {

    /** Creates new form FormLogin */
    public FormLogin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        backgroundGradient = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        separatorUsername = new javax.swing.JSeparator();
        textfieldUsername = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        separatorPassword = new javax.swing.JSeparator();
        buttonRegister = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        buttonClose = new javax.swing.JButton();
        buttonLogin = new javax.swing.JButton();
        labelDisclaimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameLogin"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jxareas/resources/images/white_logo.png"))); // NOI18N
        panelBackground.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        backgroundGradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jxareas/resources/images/black_gradient_background.png"))); // NOI18N
        panelBackground.add(backgroundGradient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 500));

        labelLogin.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        labelLogin.setText("INICIO DE SESIÓN");
        panelBackground.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        labelUsername.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        labelUsername.setText("USUARIO");
        panelBackground.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        separatorUsername.setBackground(new java.awt.Color(51, 51, 51));
        separatorUsername.setForeground(new java.awt.Color(51, 51, 51));
        panelBackground.add(separatorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 330, 20));

        textfieldUsername.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textfieldUsername.setBorder(null);
        panelBackground.add(textfieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 330, 30));

        labelPassword.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        labelPassword.setText("CONTRASEÑA");
        panelBackground.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        separatorPassword.setBackground(new java.awt.Color(51, 51, 51));
        separatorPassword.setForeground(new java.awt.Color(51, 51, 51));
        panelBackground.add(separatorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 330, 20));

        buttonRegister.setBackground(new java.awt.Color(255, 255, 254));
        buttonRegister.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        buttonRegister.setText("Regístrate");
        buttonRegister.setBorder(null);
        buttonRegister.setFocusable(false);
        panelBackground.add(buttonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 330, 30));

        passwordField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        passwordField.setBorder(null);
        panelBackground.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 330, 30));

        buttonClose.setBackground(new java.awt.Color(255, 255, 254));
        buttonClose.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        buttonClose.setText("CERRAR");
        buttonClose.setBorder(null);
        buttonClose.setFocusable(false);
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });
        panelBackground.add(buttonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 0, 100, 50));

        buttonLogin.setBackground(new java.awt.Color(0, 0, 0));
        buttonLogin.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Inicia sesión");
        buttonLogin.setBorder(null);
        buttonLogin.setFocusable(false);
        panelBackground.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 330, 30));

        labelDisclaimer.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelDisclaimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDisclaimer.setText("© 2022 Konnect. Todos los derechos reservados.");
        panelBackground.add(labelDisclaimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 420, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundGradient;
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JLabel labelDisclaimer;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JSeparator separatorPassword;
    private javax.swing.JSeparator separatorUsername;
    private javax.swing.JTextField textfieldUsername;
    // End of variables declaration//GEN-END:variables

}
